#!/bin/bash

# sudo airmon-ng stop wlx00c0cab1d64d
# sudo systemctl start NetworkManager.service
ip link set wlx00c0cab1d64d down
iw dev wlx00c0cab1d64d set type managed
ip link set wlx00c0cab1d64d up
iw dev